# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run coverage

on:
  push:

permissions:
  contents: read

jobs:
  run-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install necessary dependencies
      run: |
        python -m pip install --upgrade pip coverage
        pip install .
    - name: Run coverage without optional dependencies
      run: |
        coverage run --parallel-mode tests/test_all.py
    - name: Install optional dependencies
      run: |
        python -m pip install --upgrade regex python-dateutil
    - name: Run coverage with optional dependencies
      run: |
        coverage run --parallel-mode tests/test_all.py
    - name: Produce coverage reports
      run: |
        coverage combine
        coverage html -i
        echo '```' >> $GITHUB_STEP_SUMMARY
        coverage report -i >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
    - name: Upload htmlcov
      uses: actions/upload-artifact@v3
      with:
        name: htmlcov
        path: htmlcov/
    - name: Fail if not 100% coverage
      run: |
        coverage report -i --fail-under=100
